"""Pure domain tools for OriginFlow (Phase 3).

These modules expose deterministic logic that operate on small slices of ODL
state and return :class:`ODLPatch` objects.  They intentionally avoid direct
access to databases or global stores.  The orchestrator is responsible for
composing tools and applying the resulting patches.
"""

from . import (
    wiring,
    structural,
    monitoring,
    placeholders,
    selection,
    consensus,
    schemas,
    replacement,
    deletion,
    electrical,
    electrical_v2,
    analysis,
    standards,
    components,
    datasheets,
    comm,
    design_state,
    standards_profiles,
    standards_check_v2,
    schedules,
    explain_design_v2,
    routing,
    mechanical,
    labels,
    select_equipment,
    stringing,
    ocp_dc,
    materialize,
    bom,
    catalog,
)

__all__ = [
    "wiring",
    "structural",
    "monitoring",
    "placeholders",
    "selection",
    "consensus",
    "schemas",
    "replacement",
    "deletion",
    "electrical",
    "electrical_v2",
    "analysis",
    "standards",
    "components",
    "datasheets",
    "comm",
    "design_state",
    "standards_profiles",
    "standards_check_v2",
    "schedules",
    "explain_design_v2",
    "routing",
    "mechanical",
    "labels",
    "select_equipment",
    "stringing",
    "ocp_dc",
    "materialize",
    "bom",
    "catalog",
]
