"""add file asset table

Revision ID: 47ddfcd8b6d3
Revises: c2ac3c5e70ae
Create Date: 2025-07-15 06:55:02.551009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ddfcd8b6d3'
down_revision: Union[str, Sequence[str], None] = 'c2ac3c5e70ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_assets_id'), 'file_assets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_assets_id'), table_name='file_assets')
    op.drop_table('file_assets')
    # ### end Alembic commands ###
