"""create memory table

Revision ID: 9123abcd4567
Revises: f1a2b3c4d5e6
Create Date: 2025-08-17 00:00:00.000000

This migration adds the ``memory`` table for persisting arbitrary state
generated by OriginFlow's AI agents and end‑users.  The table mirrors
the fields defined on the ``Memory`` ORM model in
``backend/models/memory.py``:contentReference[oaicite:0]{index=0} and supports
multi‑tenant, multi‑project queries.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9123abcd4567'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create ``memory`` table.

    The ``memory`` table stores conversation histories, design snapshots
    and other persisted state produced by AI agents.  Each record is
    associated with a tenant and optionally a project, and includes
    metadata such as tags and cryptographic hashes to enable integrity
    checks.  See ``backend/models/memory.py`` for the authoritative
    model definition:contentReference[oaicite:1]{index=1}.
    """
    op.create_table(
        "memory",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.Column("sha256", sa.String(), nullable=True),
        sa.Column("prev_sha256", sa.String(), nullable=True),
    )


def downgrade() -> None:
    """Drop ``memory`` table."""
    op.drop_table("memory")
