"""Initial consolidated migration

Revision ID: b824b42b81b1
Revises: 
Create Date: 2025-07-16 04:10:55.589216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b824b42b81b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ``schematic_components`` and ``links`` tables were missing from the initial
    # migration.  They are required by the ORM models so we create them first.
    op.create_table(
        "schematic_components",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("standard_code", sa.String(), nullable=True),
        sa.Column("x", sa.Integer(), nullable=False, default=100),
        sa.Column("y", sa.Integer(), nullable=False, default=100),
    )
    op.create_index(
        "ix_schematic_components_id",
        "schematic_components",
        ["id"],
        unique=True,
    )
    op.create_table('file_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['schematic_components.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_assets_id'), 'file_assets', ['id'], unique=False)
    op.create_table(
        "links",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "source_id",
            sa.String(),
            sa.ForeignKey("schematic_components.id"),
            nullable=False,
        ),
        sa.Column(
            "target_id",
            sa.String(),
            sa.ForeignKey("schematic_components.id"),
            nullable=False,
        ),
    )
    op.create_index("ix_links_id", "links", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_id', table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_file_assets_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index('ix_schematic_components_id', table_name='schematic_components')
    op.drop_table('schematic_components')
    # ### end Alembic commands ###
