apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  namespace: monitoring
  labels:
    grafana_datasource: "1"       # Picked up by Grafana sidecar in kube-prometheus-stack
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: ${PROMETHEUS_URL}
        editable: true
        jsonData:
          httpMethod: GET
        secureJsonData: {}
