apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: originflow-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # Adjust to match your Prometheus Operator "release" label selector
spec:
  groups:
    - name: originflow-slo
      rules:
        - alert: AnalyzeLatencyHighShort
          expr: histogram_quantile(0.95, sum by (le, tenant_id) (rate(analyze_process_latency_seconds_bucket[5m]))) > 0.25
          for: 10m
          labels: { severity: page }
          annotations:
            summary: "Analyze p95 latency > 250ms (short window)"
            description: "Tenant {{ $labels.tenant_id }} p95 > 250ms for 10m."
        - alert: AnalyzeLatencyHighLong
          expr: histogram_quantile(0.95, sum by (le, tenant_id) (rate(analyze_process_latency_seconds_bucket[1h]))) > 0.20
          for: 2h
          labels: { severity: ticket }
          annotations:
            summary: "Analyze p95 latency > 200ms (sustained)"
            description: "Tenant {{ $labels.tenant_id }} p95 > 200ms for 2h."
    - name: originflow-cache
      rules:
        - alert: PolicyCacheRedisMissRateHigh
          expr: |
            (sum by (tenant_id) (rate(policy_cache_misses_total{layer="redis"}[10m]))) /
            clamp_min(sum by (tenant_id) (rate(policy_cache_hits_total{layer="redis"}[10m])) + sum by (tenant_id) (rate(policy_cache_misses_total{layer="redis"}[10m])), 1) > 0.30
          for: 30m
          labels: { severity: warn }
          annotations:
            summary: "Redis miss rate > 30% (policy cache)"
            description: "Tenant {{ $labels.tenant_id }} redis miss rate is elevated. Check caching, TTLs, and redis health."
        - alert: PolicyCacheDBFallbackRateHigh
          expr: sum by (tenant_id) (rate(policy_cache_misses_total{layer="db"}[10m])) > 0.05
          for: 30m
          labels: { severity: warn }
          annotations:
            summary: "DB fallback rate high"
            description: "Tenant {{ $labels.tenant_id }} hitting DB for policy cache frequently. Investigate redis, TTL, and dogpile."
    - name: originflow-approvals
      rules:
        - alert: ApprovalsEnqueueSpike
          expr: sum by (tenant_id) (rate(approvals_enqueued_total[5m])) > 5
          for: 15m
          labels: { severity: info }
          annotations:
            summary: "Spike in approvals enqueued"
            description: "Tenant {{ $labels.tenant_id }} enqueue rate > 5/min; review router accuracy and thresholds."
    - name: originflow-http
      rules:
        - alert: Backend5xxRateHigh
          expr: |
            sum by (tenant_id) (rate(http_requests_total{code=~"5.."}[5m])) /
            clamp_min(sum by (tenant_id) (rate(http_requests_total[5m])), 1) > 0.02
          for: 15m
          labels: { severity: page }
          annotations:
            summary: "5xx error rate > 2%"
            description: "Backend 5xx error rate is elevated for tenant {{ $labels.tenant_id }}."

    # ------------------------------------------------------------------------
    # Recording rules to precompute p95 latency and average sizes (5m window)
    # ------------------------------------------------------------------------
    - name: originflow-recording-5m
      rules:
        # HTTP latency p95 by route, tenant
        - record: http_request_duration_seconds:sum_rate5m_by_le_route_tenant
          expr: sum by (le, route, tenant_id) (rate(http_request_duration_seconds_bucket[5m]))
        - record: http_request_duration_seconds:p95_5m_by_route_tenant
          expr: histogram_quantile(0.95, http_request_duration_seconds:sum_rate5m_by_le_route_tenant)

        # Analyze pipeline latency p95 by tenant
        - record: analyze_process_latency_seconds:sum_rate5m_by_le_tenant
          expr: sum by (le, tenant_id) (rate(analyze_process_latency_seconds_bucket[5m]))
        - record: analyze_process_latency_seconds:p95_5m_by_tenant
          expr: histogram_quantile(0.95, analyze_process_latency_seconds:sum_rate5m_by_le_tenant)

        # Request size: avg & p95 by route, tenant
        - record: http_request_size_bytes:sum_rate5m_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_request_size_bytes_sum[5m]))
        - record: http_request_size_bytes:count_rate5m_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_request_size_bytes_count[5m]))
        - record: http_request_size_bytes:avg_5m_by_route_tenant
          expr: http_request_size_bytes:sum_rate5m_by_route_tenant
                / clamp_min(http_request_size_bytes:count_rate5m_by_route_tenant, 1)
        - record: http_request_size_bytes:sum_rate5m_by_le_route_tenant
          expr: sum by (le, route, tenant_id) (rate(http_request_size_bytes_bucket[5m]))
        - record: http_request_size_bytes:p95_5m_by_route_tenant
          expr: histogram_quantile(0.95, http_request_size_bytes:sum_rate5m_by_le_route_tenant)

        # Response size: avg & p95 by route, tenant
        - record: http_response_size_bytes:sum_rate5m_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_response_size_bytes_sum[5m]))
        - record: http_response_size_bytes:count_rate5m_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_response_size_bytes_count[5m]))
        - record: http_response_size_bytes:avg_5m_by_route_tenant
          expr: http_response_size_bytes:sum_rate5m_by_route_tenant
                / clamp_min(http_response_size_bytes:count_rate5m_by_route_tenant, 1)
        - record: http_response_size_bytes:sum_rate5m_by_le_route_tenant
          expr: sum by (le, route, tenant_id) (rate(http_response_size_bytes_bucket[5m]))
        - record: http_response_size_bytes:p95_5m_by_route_tenant
          expr: histogram_quantile(0.95, http_response_size_bytes:sum_rate5m_by_le_route_tenant)

    # ------------------------------------------------------------------------
    # Recording rules to precompute p95 latency and average sizes (1h window)
    # ------------------------------------------------------------------------
    - name: originflow-recording-1h
      rules:
        # HTTP latency p95 by route, tenant
        - record: http_request_duration_seconds:sum_rate1h_by_le_route_tenant
          expr: sum by (le, route, tenant_id) (rate(http_request_duration_seconds_bucket[1h]))
        - record: http_request_duration_seconds:p95_1h_by_route_tenant
          expr: histogram_quantile(0.95, http_request_duration_seconds:sum_rate1h_by_le_route_tenant)

        # Analyze pipeline latency p95 by tenant
        - record: analyze_process_latency_seconds:sum_rate1h_by_le_tenant
          expr: sum by (le, tenant_id) (rate(analyze_process_latency_seconds_bucket[1h]))
        - record: analyze_process_latency_seconds:p95_1h_by_tenant
          expr: histogram_quantile(0.95, analyze_process_latency_seconds:sum_rate1h_by_le_tenant)

        # Request size: avg & p95 by route, tenant
        - record: http_request_size_bytes:sum_rate1h_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_request_size_bytes_sum[1h]))
        - record: http_request_size_bytes:count_rate1h_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_request_size_bytes_count[1h]))
        - record: http_request_size_bytes:avg_1h_by_route_tenant
          expr: http_request_size_bytes:sum_rate1h_by_route_tenant
                / clamp_min(http_request_size_bytes:count_rate1h_by_route_tenant, 1)
        - record: http_request_size_bytes:sum_rate1h_by_le_route_tenant
          expr: sum by (le, route, tenant_id) (rate(http_request_size_bytes_bucket[1h]))
        - record: http_request_size_bytes:p95_1h_by_route_tenant
          expr: histogram_quantile(0.95, http_request_size_bytes:sum_rate1h_by_le_route_tenant)

        # Response size: avg & p95 by route, tenant
        - record: http_response_size_bytes:sum_rate1h_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_response_size_bytes_sum[1h]))
        - record: http_response_size_bytes:count_rate1h_by_route_tenant
          expr: sum by (route, tenant_id) (rate(http_response_size_bytes_count[1h]))
        - record: http_response_size_bytes:avg_1h_by_route_tenant
          expr: http_response_size_bytes:sum_rate1h_by_route_tenant
                / clamp_min(http_response_size_bytes:count_rate1h_by_route_tenant, 1)
        - record: http_response_size_bytes:sum_rate1h_by_le_route_tenant
          expr: sum by (le, route, tenant_id) (rate(http_response_size_bytes_bucket[1h]))
        - record: http_response_size_bytes:p95_1h_by_route_tenant
          expr: histogram_quantile(0.95, http_response_size_bytes:sum_rate1h_by_le_route_tenant)
