name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pipx install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install deps
        run: poetry install --no-interaction

      - name: Run unit tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///${{ github.workspace }}/.localdb/ci.db
        run: |
          mkdir -p .localdb
          poetry run pytest -q

      - name: Smoke test (plan → act → view)
        env:
          DATABASE_URL: sqlite+aiosqlite:///${{ github.workspace }}/.localdb/ci.db
        run: |
          chmod +x scripts/smoke.sh
          ./scripts/smoke.sh

